SELECT * FROM customer_behavior.customer;
#Q1. What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

#Q2. Which customer used a discount but still spent more than average purchase amount.
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and  purchase_amount >= (select avg(purchase_amount) from customer);

SELECT 
    customer_id,
    discount_applied,
    purchase_amount,
    (SELECT AVG(purchase_amount) FROM customer) AS avg_purchase_amount
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

#Q3 which are the top 5 products with the highest average review rating
select  item_purchased,round(AVG(review_rating),2) as review_rating
from customer 
group by item_purchased
order by review_rating desc limit 5;

#Q4 COMPARE THE AVEREAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING

SELECT SHIPPING_TYPE,
ROUND(avg(PURCHASE_AMOUNT),2) AS AVG_PURCHASEAMOUNT
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ("EXPRESS" , "STANDARD")
group by SHIPPING_TYPE;

#Q5. DO SUBSCRIBED customer SPEND MORE? COMPARE AVG SPEND AND TOTAL REVENUE 
#BETWEN SUBSCRIPTION AND NON SUBSCRIPTION
select subscription_status,
count(customer_id) AS TOTAL_CUSTOMERS,
round(AVG(PURCHASE_AMOUNT),2) as AVGPURCHASE_AMOUNT,
sum(purchase_amount) AS TOTAL_REVENUE
FROM customer
group by subscription_status
ORDER BY TOTAL_REVENUE,AVGPURCHASE_AMOUNT DESC;

#Q6. WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES  WITH DISCOUNT APPLIED?

SELECT Item_purchased,
ROUND (100 * SUM(CASE WHEN DISCOUNT_APPLIED = "YES" THEN 1 ELSE 0 END )/COUNT(*),2) AS DISCOUNT_RATE
FROM customer 
group by item_purchased
ORDER BY DISCOUNT_RATE desc 
limit 5;

#Q7. SEGMENT CUSTOMERS INTO NEW ,RETURNING , AND LOYAL BASED ON THEIR TOTAL 
#NYMBER OF PREVIOUS PURCHASES , AND SHOW THE COUNT OF EACH SEGMENT. 
SELECT * FROM customer_behavior.customer;

WITH CUSTOMER_TYPE AS(
SELECT CUSTOMER_ID,PREVIOUS_PURCHASES,
CASE
WHEN PREVIOUS_PURCHASES = 1 THEN "NEW"
WHEN PREVIOUS_PURCHASES between 2 AND 10 THEN "RETURNING"
ELSE "LOYAL"
END AS CUSTOMER_SEGMENT
FROM customer
)
SELECT CUSTOMER_SEGMENT ,count(*) AS "NUMBER_OF_CUSTOMERS"
FROM customer_TYPE
group by CUSTOMER_SEGMENT;


#Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT * FROM customer_behavior.customer;
SELECT 
    AGE_GROUP,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


SELECT count(CUSTOMER_ID)
FROM customer
